name: CI
on:
  push:
    branches: [main]
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g expo-cli
      - run: npm install
      - run: expo export:web -o ../web-build
      - run: npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npx serverless deploy --region us-east-1 --aws-profile default
